@extends('layouts/default')

@section('top-content')
<h1>Privacy beleid</h1>
<p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Soluta ipsum, quia aut pariatur architecto voluptas tempora quo illum aspernatur saepe maxime numquam iure consequuntur atque. Voluptates harum enim, asperiores in corrupti modi rerum architecto nostrum assumenda consequatur, iure repellat, facere consectetur sed. Vero nostrum officia sequi? Sed accusamus doloremque cum?</p>
<p>Delectus quisquam dolorem possimus velit exercitationem ab voluptate perspiciatis impedit ullam nihil quidem, non sint blanditiis dicta quos quod in itaque odio voluptatum eligendi facere obcaecati! Quia, reprehenderit iste! Commodi illo aliquid modi soluta placeat pariatur esse amet temporibus consequuntur quam dolorem omnis, tenetur doloribus debitis. Aut architecto iusto quisquam.</p>
<p>Sunt fugit maxime corporis dolores illum! Facilis quos quisquam obcaecati aperiam vel, est quis voluptatibus velit voluptates deserunt animi et rerum fugiat veritatis asperiores esse eos ipsa. Sit asperiores porro, natus nihil hic esse dolor, minima, doloribus ipsam ea nemo soluta modi! Porro soluta tempore, atque alias eaque quae odio?</p>
<p>Atque dolore explicabo est, vel adipisci animi accusamus. Vitae quasi earum at sed assumenda. Veritatis, accusamus impedit quisquam numquam aliquid quod esse sapiente, saepe neque quaerat perferendis. Commodi incidunt ducimus exercitationem dolorem nobis nulla quidem, voluptate id distinctio sunt earum alias neque repellendus consectetur? Natus ipsa modi aut illo maiores?</p>
<p>Deserunt, molestiae quasi pariatur expedita similique accusantium modi sint consectetur voluptatum hic molestias debitis possimus eius! Accusamus maiores consequuntur ab. Praesentium delectus, quos nostrum cum repellendus perferendis culpa recusandae, at vitae quod, voluptatibus neque. Maxime deserunt provident molestias corrupti. Eaque vero laudantium praesentium aut veritatis autem vitae, facilis inventore tempore!</p>
@endsection